### ISSUE TITLE
All in Gambit vs Slothie service

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/slothie#26]
## All in Gambit

Implementation ideas: https://gist.github.com/aaronschachter/49fce7aba356f1d522f8e10140a3a2a7

Pros
* Blink integration
* Single User model (Slothie + Gambit each keep a currentCampaignID, with Slothie always setting it in Gambit via keyword)
* Single place for reply logic

Cons
* Adds more complexity, tasks to already complex Campaign chatbot logic
* Make sure we don't break what's currently working
* Ideally only create Message documents for non-mData requests so we can do a bulk Mobile Commons backfill after TGM

## Separate Slothie Service

Pros
* Light weight separation of concerns -- quick reply, paused user vs Campaign conversations that require NS User lookup, DS Campaign lookup, etc.
* Don't need to worry about mData support - Gambit works as is

Cons
* How would this work with Blink?

**Comment by aaronschachter** [comment]
We're going with all in Gambit. Will keep this repo around for prototyping during TGM

**Comment by aaronschachter** [comment]
Idea for revisiting separate Gambit Conversations (this repo) and Gambit Campaigns (github.com/dosomething/gambit) services:

![receive-message](https://user-images.githubusercontent.com/1236811/28537362-69194872-705f-11e7-9020-632b29f3b463.png)

**Comment by aaronschachter** [comment]
![send-message](https://user-images.githubusercontent.com/1236811/28546118-6f229b50-707e-11e7-80c9-b77ea32295c7.png)

**Comment by aaronschachter** [comment]
Broadcasts (POST `/import-message`)
![import-message](https://user-images.githubusercontent.com/1236811/28557254-3616a472-70c0-11e7-9054-e4d5ac1cca0b.png)

**Comment by aaronschachter** [comment]
![import-message-detail](https://user-images.githubusercontent.com/1236811/28557259-3d293bf8-70c0-11e7-9d47-6929f36853ba.png)

**Comment by aaronschachter** [comment]
We've discussed as a team and are changing directions on this one -- we'll build out this app (now renamed to Gambit Conversations) to become the service that Blink will post incoming messages to. When we receive an inbound message and don't have a Rivescript reply, we send it to our tried and true [Gambit `chatbot` endpoint.](https://github.com/DoSomething/gambit/blob/4.5.8/app/routes/index.js#L32) We've been referring to [Gambit](https://github.com/dosomething/gambit) as Gambit Campaigns and will likely rename the repo accordingly in the near future.

The Conversations API will handle sending the reply message to an incoming message from a member based on the Conversation medium (`twilio`, `slack`, `facebook`)

Reasons why:
- Rivescript quick replies exist 
- Paused Conversations / Member Support messaging exists (via Front) 
- Passing off inbound messages to Gambit Campaigns and sending back the reply exists (as a hack -- new issue to be created to unhack) 
- Currently sending messages to/from Slack, Twilio, Messenger via [Slothbot placeholder webhooks.](https://github.com/DoSomething/slothbot/blob/1.8.0/app/routes/index.js)
- We only have one point of entry into Support -- via **QUESTION** keyword
- A Select Campaign **MENU** keyword exists, albeit in a very dumb form (randomly pitches a Campaign, refs https://github.com/DoSomething/gambit/issues/745#issuecomment-317875677)
- A big unknown with the 2 systems was how we manage state. We'll be managing it via the `Conversation` model and eventually no longer need the `User` model in Gambit Campaigns (we'll still need it until Blink makes the switch to start posting incoming messages to the Conversations API).

I propose we make an effort to start referring Conversation State ivs User State when chatting about how the Conversation API determines a reply message. "User State" feels vaguer that needs to be -- one may expect it to live in Northstar since it's defined on a User (or the still-will-be-around-for-a-while `User` model in Gambit Campaigns). I'm about to open an issue in this repo for discussion to finalize Schema names :neckbeard: 

cc @rapala61 @sergii-tkachenko @DFurnes

**Comment by DFurnes** [comment]
Super excited about this! Also love the Gambit Conversation / Gambit Campaigns naming. 👌
